overblog_graphql:
    definitions:
        schema:
            query: Query
            types:
                - User
                - Referrer
                - Intervention
                - Client
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
