Client:
  type: object
  inherits: [Timestampable, Node]
  config:
    interfaces: [Node]
    description: A client
    fields:
      id:
        builder: 'Relay::GlobalId'
        builderConfig:
          typeName: Client
      name:
        type: String!
        description: The company name of the client
      address:
        type: String!
        description: The address of the customer's registered office
      zipCode:
        type: String!
        description: The zip code of the customer's registered office
      slug:
        type: String!
        description: The slug of the client based on the name.
      interventions:
        type: InterventionConnection!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\InterventionsResolver", [value, args])'
        argsBuilder: Relay::Connection
        description: Interventions made at the customer's premises
        args:
          orderBy:
            type: ClientInterventionOrder
            defaultValue: { field: startAt, direction: ASC }
      referrers:
        type: '[Referrer]'
        description: The client's referrers.
