CreateClientInput:
  type: relay-mutation-input
  config:
    description: The input type of client creation.
    fields:
      name:
        type: String!
        description: The name of the client.
      address:
        type: String!
        description: The location of the client.
      zip_code:
        type: String!
        description: The zip code of client's address.
