EditClientInput:
  type: relay-mutation-input
  config:
    description: The input type of client edition.
    fields:
      name:
        type: String!
        description: The name of the client.
      address:
        type: String!
        description: The address of the client.
      zip_code:
        type: String!
        description: The zip code of client's address.
      city:
        type: String!
        description: The city of the client.
      description:
        type: String
        description: A short description of the client.
      phone:
        type: String
        description: The phone number of the client.
      client:
        type: String!
        description: The client ID.
