Intervention:
  type: object
  inherits: [Timestampable, Node]
  config:
    interfaces: [Node]
    description: An intervention
    fields:
      id:
        builder: 'Relay::GlobalId'
        builderConfig:
          typeName: Intervention
      client:
        type: '[Client]'
        description: The client receiving the intervention.
      startAt:
        description: The start date of the intervention.
        type: DateTime
      endAt:
        description: The end date of the intervention.
        type: DateTime
      inProgress:
        type: Boolean!
