Mutation:
  type: object
  config:
    fields:
      loginUser:
        access: '@=isAnonymous()'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: LoginUserInput
          payloadType: LoginUserPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\LoginUserMutation", [value, getUser()])'
      createClient:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: CreateClientInput
          payloadType: CreateClientPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Client\\CreateClientMutation", [value, getUser()])'
      editClient:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: EditClientInput
          payloadType: EditClientPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Client\\EditClientMutation", [value, getUser()])'
      deleteClient:
        access: '@=hasRole("ROLE_USER")'
        builder: 'Relay::Mutation'
        builderConfig:
          inputType: DeleteClientInput
          payloadType: DeleteClientPayload
          mutateAndGetPayload: '@=mutation("App\\GraphQL\\Mutation\\Client\\DeleteClientMutation", [value, getUser()])'
