Query:
  type: object
  config:
    fields:
      viewer:
        access: '@=isAuthenticated()'
        type: User!
        description: The currently authenticated user.
        resolve: '@=getUser()'
      node:
        builder: Relay::Node
        builderConfig:
          nodeInterfaceType: Node
          idFetcher: '@=resolver("App\\GraphQL\\Resolver\\GlobalIdResolver", [value])'
      clients:
        description: Get all clients.
        type: ClientConnection!
        argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\ClientsResolver", [args])'
      client:
        description: Get one client.
        type: Client!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\ClientResolver", [args])'
        args:
          search: ClientSearch!
      interventionTypes:
        description: Get all intervention types.
        type: InterventionTypeConnection!
        argsBuilder: Relay::Connection
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\InterventionTypesResolver", [args])'
      intervention:
        description: Get one intervention.
        type: Intervention!
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\InterventionResolver", [args])'
      businessSegments:
        description: Get all business segments.
        type: '[BusinessSegment]'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\Query\\BusinessSegmentsResolver", [args])'